[package]
name = "wr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
rand = "0.8.4"
indicatif = "0.15.0"

[[bin]]
name = "wr"
path = "main.rs"

